# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 598c20fe0227bb717e0c0e50139f0478de1257f854f10d0ed4ac523ec854f569f5bf1266eba1bec61997bbf73728af3951a37175eb78b4a74df521c7fe02de96

test:
  secret_key_base: 25ce751718a6bdb7e9582571eb1c324bf4d604c70e872fe6f74a43d6142094b86ee6e7c9087d5afda6e3ca02226a2a6b3739121401554b3676ccc8f8d2e80b6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
